### ISSUE TITLE
What is the correct nuget package?

### ISSUE THREAD

**Issue by ignatandrei** [Cricle/StaticReflection#2]
Apparently, are 2 packages
https://www.nuget.org/packages/FastStaticReflection.CodeGen/#versions-body-tab
https://www.nuget.org/packages/FastStaticReflection/#versions-body-tab

What is the correct package? 
( I want to add this package to my list of Roslyn, https://ignatandrei.github.io/RSCG_Examples/v2/docs/List-of-RSCG )
Thanks
Andrei

**Comment by Cricle** [comment]
Actually the package FastStaticReflection is model define, the package FastStaticReflection.CodeGen will generate code when compiled time.

The generated code reference FastStaticReflection class, interface and others.

Thanks.

**Comment by ignatandrei** [comment]
Thanks ( the link will be https://ignatandrei.github.io/RSCG_Examples/v2/docs/StaticReflection )
Andrei
